services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: symfony_todo
      POSTGRES_USER: app
      POSTGRES_PASSWORD: ChangeMe
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    volumes:
      # Synchronizuj zdrojové kódy
      - ./src:/app/src:delegated
      - ./config:/app/config:delegated
      - ./templates:/app/templates:delegated
      - ./public:/app/public:delegated
      - ./migrations:/app/migrations:delegated
      - ./.env:/app/.env:delegated
      # Ponech vendor z kontejneru
      # Použij pojmenovaný svazek pro var
      - var_data:/app/var
    ports:
      - "8000:80"

volumes:
  db_data:
  var_data: 